# syntax=docker/dockerfile:1

# Base image is pinned by digest for reproducible, tamper-evident builds.
# Dependabot keeps the tag + digest current (see .github/dependabot.yml).
ARG ALPINE_VERSION=3.24
ARG ALPINE_DIGEST=sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

# NUT release to compile. See https://www.networkupstools.org/source/2.8/
ARG NUT_VERSION=2.8.5


# ---- Build stage: compile NUT from a cryptographically verified tarball ----
FROM alpine:${ALPINE_VERSION}@${ALPINE_DIGEST} AS build

ARG NUT_VERSION

# hadolint ignore=DL3018
RUN set -eux; \
	apk add --no-cache \
		build-base \
		ca-certificates \
		gnupg \
		libusb-compat-dev \
	; \
	cd /tmp; \
	tarball="nut-${NUT_VERSION}.tar.gz"; \
	wget -q "https://www.networkupstools.org/source/2.8/${tarball}"; \
	wget -q "https://www.networkupstools.org/source/2.8/${tarball}.sig"; \
	# Verify authenticity against the official NUT signing keyring (fetched over TLS).
	# Historically 2.8.0 shipped unsigned, which is why the original image skipped this;
	# 2.8.5 is properly signed, so we now require a good signature to build.
	GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
	wget -q -O nut-key.gpg "https://www.networkupstools.org/source/nut-key.gpg"; \
	gpg --batch --import nut-key.gpg; \
	gpg --batch --verify "${tarball}.sig" "${tarball}"; \
	gpgconf --kill all || true; \
	# Build.
	tar -xzf "${tarball}"; \
	cd "nut-${NUT_VERSION}"; \
	./configure \
		--prefix=/usr \
		--sysconfdir=/etc/nut \
		--disable-dependency-tracking \
		--enable-strip \
		--disable-static \
		--with-all=no \
		--with-usb=yes \
		--datadir=/usr/share/nut \
		--with-drvpath=/usr/share/nut \
		--with-statepath=/var/run/nut \
		--with-user=nut \
		--with-group=nut \
	; \
	make -j "$(nproc)"; \
	make install DESTDIR=/install


# ---- Runtime stage: minimal image with only the compiled binaries + runtime deps ----
FROM alpine:${ALPINE_VERSION}@${ALPINE_DIGEST}

ARG NUT_VERSION

LABEL org.opencontainers.image.title="nut-upsd" \
      org.opencontainers.image.description="Network UPS Tools (NUT) server for USB-attached UPS monitoring" \
      org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.version="${NUT_VERSION}"

# Passwords are intentionally NOT declared here: they are supplied at run time
# (env, *_FILE secret, or auto-generated by the entrypoint). Declaring them as
# ENV would bake empty secret-named values into the image.
ENV UPS_NAME="ups" \
    UPS_DESC="UPS" \
    UPS_DRIVER="usbhid-ups" \
    UPS_PORT="auto" \
    SHUTDOWN_CMD="echo 'System shutdown not configured!'"

# hadolint ignore=DL3018
RUN set -eux; \
	apk add --no-cache \
		libusb-compat \
		openssh-client \
		tini \
	; \
	adduser -D -h /var/run/nut nut

# Copy the compiled tree (binaries, libraries, drivers, config templates).
COPY --from=build /install/usr /usr
COPY --from=build /install/etc/nut /etc/nut

RUN set -eux; \
	chown -R root:nut /etc/nut; \
	chmod 750 /etc/nut; \
	install -d -m 750 -o nut -g nut /var/run/nut

COPY docker-entrypoint /usr/local/bin/

# upsd answers on 3493; treat an unreadable UPS as unhealthy.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
	CMD upsc "${UPS_NAME}@localhost" >/dev/null 2>&1 || exit 1

# tini as PID 1 reaps zombies and forwards signals to the daemons.
ENTRYPOINT ["/sbin/tini", "--", "docker-entrypoint"]

WORKDIR /var/run/nut

EXPOSE 3493
