name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image and push
      run: |
        docker build . --tag ghcr.io/anacozero/nut-upsd:latest
        docker push ghcr.io/anacozero/nut-upsd:latest
